name: E2E Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install pnpm
        run: npm install -g pnpm@10.17.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Start server, wait, and run smoke tests
        shell: bash
        run: |
          set -euo pipefail
          pnpm run start:test &
          SERVER_PID=$!
          echo "Started server with PID ${SERVER_PID}"
          trap 'echo "Stopping server ${SERVER_PID}"; kill ${SERVER_PID} || true' EXIT

          echo "Waiting for http://localhost:3000 ..."
          for i in {1..120}; do
            if curl -sf http://localhost:3000 >/dev/null; then
              echo "Server is up"; break; fi
            sleep 1
          done
          # Verify server became healthy; curl returns non-zero when not up
          curl -sf http://localhost:3000 >/dev/null

          pnpm run test:e2e:smoke

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: web/playwright-report


