name: E2E Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.17.1 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and start app
        run: pnpm run start:test &

      - name: Wait for server
        run: |
          for i in {1..60}; do
            if curl -sSf http://localhost:3000 >/dev/null; then
              echo "Server is up"; exit 0; fi; sleep 1; done
          echo "Server failed to start"; exit 1

      - name: Run E2E smoke tests
        run: pnpm run test:e2e:smoke

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: web/playwright-report


